Fixes #77
opencodeiiita/CodeFemme pull request #84
Opened 2019-02-07 05:39 UTC by Archies11

# Description

Added scrollspy and changed hover effect to underline in navbar.

Fixes #77

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Live Gh-Pages Link
[Live Link] https://focused-snyder-33ef50.netlify.com/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2019-02-08 04:33 UTC, Anupam-dagar requested changes
I can't see the scrollspy happening, also change the underline to some good looking one, according to website color scheme, a purple one sounds good to me or a gradient one according to landing page. Also maybe try to underline not completely.
Also give a meaningful title to your PR. Only fixes isn't any good. You should write fixes in the description not in the title.

2019-02-08 04:34 UTC, Anupam-dagar requested changes
left some comments

2019-02-08 04:34 UTC, Anupam-dagar commented on index.html
> +  }
are you completely sure of this?

2019-02-11 17:14 UTC, Anupam-dagar commented
@Archies11 updates?

2019-02-11 18:55 UTC, Archies11 commented
@Anupam-dagar I tried to add scrollspy by following the instructions on different blogs and websites for bootstrap version used in the code but somehow I am unable to activate the feature. Is there any link that might help me with the same?

2019-02-12 05:04 UTC, Anupam-dagar commented
This might help https://getbootstrap.com/docs/4.0/components/scrollspy/

2019-02-12 09:42 UTC, Archies11 commented
> This might help https://getbootstrap.com/docs/4.0/components/scrollspy/

I did read this Blog and implement the same but it didnt work :(

2019-02-12 14:12 UTC, Anupam-dagar commented
@Archies11 check on codepen.

2019-02-14 09:26 UTC, closed without merging